import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar/page";
import Sidebar from "../components/Sidebar/page";
import Footer from "../components/Footer/page";
import Breadcrumb from "../components/Breadcrumbs/page";
import SidebarProvider from "../context/SidebarProvider";
import AuthProvider from "../context/AuthProvider";
import CunninghamStyleProvider from "../context/CunninghamProvider";

export const metadata: Metadata = {
  title: "Esup POD V5",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CunninghamStyleProvider>
        <AuthProvider>
          <SidebarProvider>
            <body>
              <Navbar />
              <Sidebar />
              <main id="main" className="main sidebarFixed">
                <Breadcrumb />
                <div className="content">{children}</div>
              </main>
              <Footer />
            </body>
          </SidebarProvider>
        </AuthProvider>
      </CunninghamStyleProvider>
    </html>
  );
}
