import type { Metadata, Viewport } from "next";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Sidebar from "../components/Sidebar/Sidebar";
import Footer from "../components/Footer/Footer";
import Breadcrumb from "../components/Breadcrumbs/Breadcrumbs";
import SidebarProvider from "../context/SidebarProvider";
import AuthProvider from "../context/AuthProvider";
import CunninghamStyleProvider from "../context/CunninghamProvider";
import DatePickerProvider from "../context/DatePickerProvider";
import AuthStatusAlert from "../components/Notifications/AuthStatusAlert";

export const metadata: Metadata = {
  title: "Esup POD V5",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  /*maximumScale: 1,*/
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <div className="layout">
          <CunninghamStyleProvider>
            <DatePickerProvider>
              <AuthProvider>
                <SidebarProvider>
                  <Navbar />
                  <Sidebar />
                  <main id="main" className="main">
                    <Breadcrumb />
                    <div className="content">
                      <AuthStatusAlert autoDismissMs={5000} />
                      {children}
                    </div>
                  </main>
                  <Footer />
                </SidebarProvider>
              </AuthProvider>
            </DatePickerProvider>
          </CunninghamStyleProvider>
        </div>
      </body>
    </html>
  );
}
